development:
  adapter: postgresql
  database: sample_app_dev
  username: postgressvc
  password:
  host: localhost
  encoding: UTF8

test:
  adapter: postgresql
  database: sample_app_test
  username: postgressvc
  password:
  host: localhost
  encoding: UTF8

production:
  adapter: postgresql
  database: sample_app_prod
  username: postgressvc
  password:
  host: localhost
  encoding: UTF8